# Generated by Django 3.2.3 on 2021-06-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiQuotaPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_slug', models.CharField(choices=[('azure', 'azure')], max_length=99)),
                ('endpoint_slug', models.CharField(choices=[('azure:named-entity-recognition', 'azure:named-entity-recognition')], max_length=99)),
                ('account_slug', models.CharField(max_length=99)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration_slug', models.CharField(choices=[('minute', 'minute'), ('quarter-hour', 'quarter-hour'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('month', 'month')], max_length=99)),
                ('units_remaining', models.IntegerField()),
            ],
        ),
    ]
