# Generated by Django 3.2.3 on 2021-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_apiquotaperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiquotaperiod',
            name='endpoint_slug',
            field=models.CharField(choices=[('azure:named-entity-recognition', 'azure:named-entity-recognition'), ('twitter:user-info', 'twitter:user-info'), ('twitter:user-timeline', 'twitter:user-timeline')], max_length=99),
        ),
        migrations.AlterField(
            model_name='apiquotaperiod',
            name='service_slug',
            field=models.CharField(choices=[('azure', 'azure'), ('twitter', 'twitter')], max_length=99),
        ),
    ]
