# Generated by Django 3.2.4 on 2021-06-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20210608_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategory',
            name='tags',
            field=models.ManyToManyField(related_name='categories', to='twitter.Tag'),
        ),
    ]
